name: pinterestmobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.6.0
  lottie: ^2.7.0
  carousel_slider: ^4.2.1
  provider: ^6.1.1
  logger: ^2.0.2+1
  dio: ^5.4.0
  permission_handler: ^11.0.1
  image_gallery_saver: ^2.0.3
  flutter_svg: ^1.1.3
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/